apiVersion: v1
kind: Service
metadata:
  labels:
    app: mnist-classifier
  name: mnist-classifier
spec:
  ports:
    - name: classify
      port: 3000
      targetPort: 3000
  selector:
    app: mnist-classifier
  type: LoadBalancer
